version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: app_srv
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: nginx_srv
    restart: unless-stopped
    tty: true
    environment:
      BASE_DOMAIN: ${BASE_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./data/logs:/var/log/nginx/
    networks:
      - app-network

  #MySQL Service
  db:
    image: percona:5.7.22
    container_name: mysql_srv
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  #Phpadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local